---
- name: Instalar qemu
  ansible.builtin.package:
    name: "{{ qemu_packages }}"
    update_cache: true
    cache_valid_time: 3600

- name: Agregar usuarios a grupos
  ansible.builtin.user:
    name: "{{ usuario }}"
    groups: "{{ item }}"
    append: true
  loop: [ 'libvirt', 'libvirt-qemu' ]
  notify: iniciar_libvirtd




