---
- hosts: testing
  become: true
  gather_facts: true

  vars_files:
    - vars_main.yml

  roles:
    - brave
    - tools
    - codium
    - nano
    - tmux
    - qemu
    - vagrant
    - ohmybash
    - bashrc
