---
- name: Instalar dependencias
  ansible.builtin.apt:
    name: [ 'curl', 'fonts-powerline' ]
    update_cache: true
    cache_valid_time: 3600

- name: Chequear si "Oh My Bash" esta instalado
  ansible.builtin.stat:
    path: "/home/{{ usuario }}/.oh-my-bash"
  register: oh_my_bash_installed

- name: Descargar + Ejecutar script
  ansible.builtin.shell: bash -c "$(curl -fsSL {{ ohmybash_installer }})"
  become_user: "{{ usuario }}"
  async: 25
  poll: 25
  ignore_errors: true
  when: not oh_my_bash_installed.stat.exists
