---
- name: Instalar tmux + dependencias
  ansible.builtin.apt:
    name: [ 'python3-apt', 'tmux', 'gawk', 'perl', 'sed' ]
    update_cache: true
    cache_valid_time: 3600

- name: copiar archivos de configuracion
  ansible.builtin.copy:
    src: "{{ item.origen }}"
    dest: "{{ item.destino }}"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0755
  with_items:
    - { origen: 'tmux.conf', destino: '/home/{{ usuario }}/.tmux.conf' }
    - { origen: 'tmux.conf.local', destino: '/home/{{ usuario }}/.tmux.conf.local' }


